// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
window.wailsbindings = {"main":{"App":{"ChangeRightWindowStyle":{"name":"main.App.ChangeRightWindowStyle","inputs":[{"type":"string"},{"type":"string"},{"type":"string"}],"outputs":[{"type":"string"}]},"ExportConn":{"name":"main.App.ExportConn"},"GetNodeData":{"name":"main.App.GetNodeData","inputs":[{"type":"string"},{"type":"string"},{"type":"string"}],"outputs":[{"type":"string"}]},"ImportConn":{"name":"main.App.ImportConn"},"LoadingConnInfo":{"name":"main.App.LoadingConnInfo","inputs":[{"type":"string"},{"type":"string"}],"outputs":[{"type":"string"}]},"LoadingConnKey":{"name":"main.App.LoadingConnKey","outputs":[{"type":"string"}]},"LoadingDbResource":{"name":"main.App.LoadingDbResource","inputs":[{"type":"string"}],"outputs":[{"type":"string"}]},"Ok":{"name":"main.App.Ok","inputs":[{"type":"string"}],"outputs":[{"type":"string"}]},"RedisDelKey":{"name":"main.App.RedisDelKey","inputs":[{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"}]},"RedisGetData":{"name":"main.App.RedisGetData","inputs":[{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"}],"outputs":[{"type":"string"}]},"RedisReName":{"name":"main.App.RedisReName","inputs":[{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"}]},"RedisSaveStringValue":{"name":"main.App.RedisSaveStringValue","inputs":[{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"}]},"RedisUpTtl":{"name":"main.App.RedisUpTtl","inputs":[{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"},{"type":"string"}]},"TestConnection":{"name":"main.App.TestConnection","inputs":[{"type":"string"}]}}}};
const go = {
  "main": {
    "App": {
      /**
       * ChangeRightWindowStyle
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "ChangeRightWindowStyle": (arg1, arg2, arg3) => {
        return window.go.main.App.ChangeRightWindowStyle(arg1, arg2, arg3);
      },
      /**
       * ExportConn
       * @returns {Promise<void>} 
       */
      "ExportConn": () => {
        return window.go.main.App.ExportConn();
      },
      /**
       * GetNodeData
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetNodeData": (arg1, arg2, arg3) => {
        return window.go.main.App.GetNodeData(arg1, arg2, arg3);
      },
      /**
       * ImportConn
       * @returns {Promise<void>} 
       */
      "ImportConn": () => {
        return window.go.main.App.ImportConn();
      },
      /**
       * LoadingConnInfo
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "LoadingConnInfo": (arg1, arg2) => {
        return window.go.main.App.LoadingConnInfo(arg1, arg2);
      },
      /**
       * LoadingConnKey
       * @returns {Promise<string>}  - Go Type: string
       */
      "LoadingConnKey": () => {
        return window.go.main.App.LoadingConnKey();
      },
      /**
       * LoadingDbResource
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "LoadingDbResource": (arg1) => {
        return window.go.main.App.LoadingDbResource(arg1);
      },
      /**
       * Ok
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Ok": (arg1) => {
        return window.go.main.App.Ok(arg1);
      },
      /**
       * RedisDelKey
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @returns {Promise<void>} 
       */
      "RedisDelKey": (arg1, arg2, arg3, arg4) => {
        return window.go.main.App.RedisDelKey(arg1, arg2, arg3, arg4);
      },
      /**
       * RedisGetData
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "RedisGetData": (arg1, arg2, arg3, arg4) => {
        return window.go.main.App.RedisGetData(arg1, arg2, arg3, arg4);
      },
      /**
       * RedisReName
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @param {string} arg5 - Go Type: string
       * @returns {Promise<void>} 
       */
      "RedisReName": (arg1, arg2, arg3, arg4, arg5) => {
        return window.go.main.App.RedisReName(arg1, arg2, arg3, arg4, arg5);
      },
      /**
       * RedisSaveStringValue
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @param {string} arg5 - Go Type: string
       * @param {string} arg6 - Go Type: string
       * @returns {Promise<void>} 
       */
      "RedisSaveStringValue": (arg1, arg2, arg3, arg4, arg5, arg6) => {
        return window.go.main.App.RedisSaveStringValue(arg1, arg2, arg3, arg4, arg5, arg6);
      },
      /**
       * RedisUpTtl
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @param {string} arg5 - Go Type: string
       * @returns {Promise<void>} 
       */
      "RedisUpTtl": (arg1, arg2, arg3, arg4, arg5) => {
        return window.go.main.App.RedisUpTtl(arg1, arg2, arg3, arg4, arg5);
      },
      /**
       * TestConnection
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "TestConnection": (arg1) => {
        return window.go.main.App.TestConnection(arg1);
      },
    },
  },

};
export default go;
