// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * LoadingConnectionInfo
       * @returns {Promise<string>}  - Go Type: string
       */
      "LoadingConnectionInfo": () => {
        return window.go.main.App.LoadingConnectionInfo();
      },
      /**
       * Ok
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Ok": (arg1) => {
        return window.go.main.App.Ok(arg1);
      },
      /**
       * TestConnection
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "TestConnection": (arg1) => {
        return window.go.main.App.TestConnection(arg1);
      },
    },
  },

};
export default go;
