// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetNodeData
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetNodeData": (arg1, arg2, arg3) => {
        return window.go.main.App.GetNodeData(arg1, arg2, arg3);
      },
      /**
       * LoadingConnInfo
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "LoadingConnInfo": (arg1) => {
        return window.go.main.App.LoadingConnInfo(arg1);
      },
      /**
       * LoadingConnKey
       * @returns {Promise<string>}  - Go Type: string
       */
      "LoadingConnKey": () => {
        return window.go.main.App.LoadingConnKey();
      },
      /**
       * LoadingDbResource
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "LoadingDbResource": (arg1) => {
        return window.go.main.App.LoadingDbResource(arg1);
      },
      /**
       * Ok
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Ok": (arg1) => {
        return window.go.main.App.Ok(arg1);
      },
      /**
       * RedisGetData
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "RedisGetData": (arg1, arg2, arg3, arg4) => {
        return window.go.main.App.RedisGetData(arg1, arg2, arg3, arg4);
      },
      /**
       * RedisReName
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @param {string} arg3 - Go Type: string
       * @param {string} arg4 - Go Type: string
       * @param {string} arg5 - Go Type: string
       * @returns {Promise<void>} 
       */
      "RedisReName": (arg1, arg2, arg3, arg4, arg5) => {
        return window.go.main.App.RedisReName(arg1, arg2, arg3, arg4, arg5);
      },
      /**
       * TestConnection
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "TestConnection": (arg1) => {
        return window.go.main.App.TestConnection(arg1);
      },
    },
  },

};
export default go;
