/*
 * @Author: symbol
 * @Date: 2022-04-29 15:10:25
 * @LastEditors: symbol
 * @LastEditTime: 2022-04-29 18:34:25
 * @FilePath: /todb/frontend/wailsjs/go/main/App.js
 * @Description:
 *
 * Copyright (c) 2022 by symbol, All Rights Reserved.
 */
// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RedisUpTtl(arg1, arg2, arg3, arg4, arg5) {
  window["go"]["main"]["App"]["RedisUpTtl"](arg1, arg2, arg3, arg4, arg5);
}

export function TestConnection(arg1) {
  window["go"]["main"]["App"]["TestConnection"](arg1);
}

export function GetNodeData(arg1, arg2, arg3) {
  return window["go"]["main"]["App"]["GetNodeData"](arg1, arg2, arg3);
}

export function LoadingConnKey() {
  return window["go"]["main"]["App"]["LoadingConnKey"]();
}

export function Ok(arg1) {
  return window["go"]["main"]["App"]["Ok"](arg1);
}

export function RedisGetData(arg1, arg2, arg3, arg4) {
  return window["go"]["main"]["App"]["RedisGetData"](arg1, arg2, arg3, arg4);
}

export function RedisReName(arg1, arg2, arg3, arg4, arg5) {
  window["go"]["main"]["App"]["RedisReName"](arg1, arg2, arg3, arg4, arg5);
}

export function BuildCommand(arg1, arg2, arg3, arg4) {
  return window["go"]["main"]["App"]["BuildCommand"](arg1, arg2, arg3, arg4);
}

export function LoadingConnInfo(arg1) {
  return window["go"]["main"]["App"]["LoadingConnInfo"](arg1);
}

export function LoadingDbResource(arg1) {
  return window["go"]["main"]["App"]["LoadingDbResource"](arg1);
}

export function RedisDelKey(arg1, arg2, arg3, arg4) {
  window["go"]["main"]["App"]["RedisDelKey"](arg1, arg2, arg3, arg4);
}
