// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadingDbResource(arg1:string):Promise<string>;

export function RedisDelKey(arg1:string,arg2:string,arg3:string,arg4:string):void;

export function RedisUpTtl(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):void;

export function TestConnection(arg1:string):void;

export function GetNodeData(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LoadingConnInfo(arg1:string):Promise<string>;

export function LoadingConnKey():Promise<string>;

export function Ok(arg1:string):Promise<string>;

export function RedisGetData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RedisReName(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):void;

export function BuildCommand(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
